defaults: &defaults
  bucket: frustrationme
  access_key_id:     <%= ENV['S3_ACCESS_KEY_ID']     %>
  secret_access_key: <%= ENV['S3_SECRET_ACCESS_KEY'] %>
  s3_host_name:      <%= ENV['S3_HOST_NAME']         %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults